// demo/solid-test.ts
import { createComponent, createSignal } from "solid-js";
import { hydrate, render } from "solid-js/web";
import { RollingNumber } from "../src/solid";
import type { RollingNumberOptions } from "../src/index";
import "../src/styles.css";

declare global {
  interface Window {
    solidReady: boolean;
    mountSolid(html?: string): void;
    updateSolid(options: Partial<RollingNumberOptions>): void;
    disposeSolid(): void;
    solidRef: HTMLSpanElement | undefined;
  }
}
const fixture = document.getElementById("fixture")!;
window.mountSolid = (html) => {
  const [options, setOptions] = createSignal<RollingNumberOptions>({ value: 1234.56, locales: "en-US", duration: 800, pauseOffscreen: false });
  window.updateSolid = (next) => setOptions((current) => ({ ...current, ...next }));
  const component = () => createComponent(RollingNumber, {
    get value() { return options().value; },
    get locales() { return options().locales; },
    get format() { return options().format; },
    get duration() { return options().duration; },
    get animated() { return options().animated; },
    pauseOffscreen: false,
    id: "solid-number",
    class: "balance",
    style: { "font-size": "64px" },
    ref: (element) => { window.solidRef = element; },
  });
  if (html !== undefined && !fixture.hasChildNodes()) fixture.innerHTML = html;
  window.disposeSolid = html === undefined ? render(component, fixture) : hydrate(component, fixture);
};
window.solidReady = true;

// demo/test.tsx
import { StrictMode } from "react";
import { createRoot, hydrateRoot, type Root } from "react-dom/client";
import { renderToString } from "react-dom/server";
import { createRollingNumber, type RollingNumberController, type RollingNumberOptions } from "../src/index";
import { RollingNumber } from "../src/react";
import "../src/styles.css";

declare global {
  interface Window {
    testNumber: RollingNumberController;
    mountNumber(options: RollingNumberOptions): void;
    reactNumber(options: RollingNumberOptions, hydrate?: boolean): void;
    unmountReact(): void;
    ready: boolean;
  }
}
const fixture = document.getElementById("fixture")!;
let react: Root | undefined;
window.mountNumber = (options) => {
  window.testNumber?.destroy();
  fixture.replaceChildren();
  const span = document.createElement("span");
  span.id = "number";
  span.style.cssText = "font: 64px/1.2 Georgia,serif; font-variant-numeric:tabular-nums";
  fixture.append(span);
  window.testNumber = createRollingNumber(span, { pauseOffscreen: false, ...options });
};
window.reactNumber = (options, hydrate = false) => {
  const element = <StrictMode><RollingNumber {...options} id="react-number" style={{ fontSize: 64 }} /></StrictMode>;
  if (!react) {
    if (hydrate) {
      fixture.innerHTML = renderToString(element);
      react = hydrateRoot(fixture, element);
    } else react = createRoot(fixture);
  }
  if (!hydrate) react.render(element);
};
window.unmountReact = () => { react?.unmount(); react = undefined; };
window.ready = true;
